# Generated by Django 3.2.8 on 2021-11-16 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.TextField(max_length=100, verbose_name='Инструмент')),
                ('song_name', models.TextField(max_length=100, verbose_name='Песня')),
                ('song_text', models.TextField(verbose_name='Текст песни')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['song_name'],
            },
        ),
    ]
