# Generated by Django 3.2.8 on 2021-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='instrument',
            field=models.CharField(max_length=100, verbose_name='Инструмент'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=100, verbose_name='Песня'),
        ),
    ]
