# Generated by Django 3.2.8 on 2021-11-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosmokingstages',
            options={'ordering': ['id']},
        ),
    ]
