# Generated by Django 3.2.8 on 2021-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('male', models.BooleanField(verbose_name='Пол')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('birthdate_checked', models.BooleanField(verbose_name='ДР проверено')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
